{% set name = "mmcif" %}
{% set version = "0.46" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "1f209405c7e89bf04835a9006c9ab8e360a1650d9020c0242b8e5bbaab44a850"

build:
  number: 0

requirements:
  host:
    - future
    - pip
    - python
    - six
    - cmake
    - flex
    - bison
  run:
    - future
    - python
    - six

test:
  imports:
    - mmcif
    - mmcif.api
    - mmcif.core
    - mmcif.io
  requires:
    - tox

about:
  home: "http://mmcif.wwpdb.org"
  license: "Apache Software"
  license_family: "APACHE"
  license_file: ""
  summary: "mmCIF Core Access Library"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - tpeulen
