{% set name = "pycorrfit" %}
{% set version = "1.1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/FCS-analysis/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d833bbee2d3864b23b95a1502e528ad5dec01fbeee85d7d57a1f67152f91d887

build:
  number: 0
  entry_points:
    - pycorrfit=pycorrfit.gui.main:Main
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
  host:
    - python {{ python }}
    - pip
    - setuptools
    - simplejson
    - cython
    - pytest-runner
    - numpy
    - lmfit >=0.9.2
    - pyyaml >=3.12
    - scipy >=1.0.1
    - matplotlib >=2.2.2
    - sympy >=1.1.1
    - wxpython
  run:
    - python {{ python }}
    - numpy
    - lmfit >=0.9.2
    - pyyaml >=3.12
    - scipy >=1.0.1
    - matplotlib >=2.2.2
    - sympy >=1.1.1
    - simplejson
    - wxpython
    - vs2015_runtime # [win]

test:
  imports:
    - pycorrfit
    - pycorrfit.models
    - pycorrfit.readfiles
    - pycorrfit.readfiles.read_pt3_scripts
  commands:
    - pycorrfit --help
  requires:
    - pytest
    - simplejson
    - urllib3

about:
  home: "https://github.com/FCS-analysis/PyCorrFit"
  license: "GPL v2"
  license_family: "GPL2"
  summary: "Scientific tool for fitting correlation curves on a logarithmic plot."
  doc_url: "https://github.com/FCS-analysis/PyCorrFit/wiki/PyCorrFit_doc.pdf"
  dev_url: "https://github.com/FCS-analysis/PyCorrFit"

extra:
  recipe-maintainers:
    - tpeulen
