{% set name = "pymol-open-source" %}
{% set version="v2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/schrodinger/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 62aa21fafd1db805c876f89466e47513809f8198395e1f00a5f5cc40d6f40ed0

build:
  number: 1

requirements:
  build:
    - python {{ python }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pyopengl
    - numpy
    - glew
    - libpng
    - freetype
    - msgpack-c
    - pyqt
    - glm
    - pkg-config                     # [linux]
    - mesalib                        # [linux]
    - libglu                         # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
  host:
    - python {{ python }}
    - pyopengl
    - numpy
    - glew
    - libpng
    - freetype
    - msgpack-c
    - glm
    - libglu # [linux]
    - {{ cdt('mesa-libgl') }} # [linux]
    - {{ cdt('libxxf86vm') }} # [linux]
  run:
    - python {{ python }}
    - pyopengl
    - pyqt
    - numpy
    - glew
    - libpng
    - freetype
    - msgpack-c
    - glm

app:
  entry: pymol
  summary: PyMOL is a molecular visualization system.
  type: desk
  icon: icon.svg

about:
  home: https://github.com/schrodinger/pymol-open-source
  summary: PyMOL is a molecular visualization system.
  description: |
    PyMOL is computer software, a molecular visualization system created by Warren Lyford DeLano. It is user-sponsored,
    open-source software, released under the Python License. It was commercialized initially by DeLano Scientific LLC,
    which was a private software company dedicated to creating useful tools that become universally accessible to
    scientific and educational communities. It is currently commercialized by Schrödinger, Inc. PyMOL can produce
    high-quality 3D images of small molecules and biological macromolecules, such as proteins. According to the original
    author, by 2009, almost a quarter of all published images of 3D protein structures in the scientific literature were
    made using PyMOL.

extra:
  recipe-maintainers:
    - tpeulen
