{% set name = "pymol-open-source" %}
{% set version="2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/schrodinger/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5ede4ce2e8f53713c5ee64f5905b2d29bf01e4391da7e536ce8909d6b9116581

build:
  number: 1

requirements:
  build:
    - python {{ python }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pyqt
    - pyopengl
    - libpng
    - glew=2.0.0
    - freetype
    - glm=0.9.9.4
    - pkg-config                     # [linux]
    - mesalib                        # [linux]
    - libglu                         # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
  host:
    - python {{ python }}
    - pyopengl
    - glew=2.0.0
    - freetype
    - glm=0.9.9.4
    - libpng
    - libglu                  # [linux]
    - {{ cdt('mesa-libgl') }} # [linux]
    - {{ cdt('libxxf86vm') }} # [linux]
  run:
    - python {{ python }}
    - pyopengl
    - pyqt
    - libpng
    - glew=2.0.0
    - freetype
    - glm=0.9.9.4

app:
  entry: pymol
  summary: PyMOL is a molecular visualization system.
  type: desk
  icon: icon.svg

about:
  home: https://github.com/schrodinger/pymol-open-source
  summary: PyMOL is a molecular visualization system.
  description: |
    PyMOL is computer software, a molecular visualization system created by Warren Lyford DeLano. It is user-sponsored,
    open-source software, released under the Python License. It was commercialized initially by DeLano Scientific LLC,
    which was a private software company dedicated to creating useful tools that become universally accessible to
    scientific and educational communities. It is currently commercialized by Schrödinger, Inc. PyMOL can produce
    high-quality 3D images of small molecules and biological macromolecules, such as proteins. According to the original
    author, by 2009, almost a quarter of all published images of 3D protein structures in the scientific literature were
    made using PyMOL.

extra:
  recipe-maintainers:
    - tpeulen
