{% set name = "quest" %}
{% set version="191013" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fluorescence-tools/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 58d592343b0552bd7fac56c09fe45e888bd3116cb5b33939c7409ae3ed8dd67e

build:
  number: 0
  entry_points:
    - quest=quest.quest_gui:start_gui

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - setuptools
    - cython
    - numpy
  run:
    - python {{ python }}
    - pyqt>=5.6.0
    - numpy
    - numexpr
    - guiqwt
    - pyopengl
    - pymol-open-source
    - libstdcxx-ng # [linux]
    - labellib

about:
  home: https://github.com/Fluorescence-Tools/quest
  license: MIT
  license_file: LICENSE
  summary: QuEst is a protein structure based fluorescence quenching estimator
  description:
    QuEst is a structure based fluorescence quenching estimator that simulates dynamic
    quenching of fluorescence decays of dyes that are coupled to the surface of a proteins.
    Dynamic fluorescence quenching is simulated by modelling (i) the diffusion of the dye
    and (ii) the quenching of the dye by surface exposed aromatic amino-acids.
extra:
  recipe-maintainers:
    - tpeulen
