package:
  name: quest
  version: "2019.08.11"

source:
  git_url: https://github.com/Fluorescence-Tools/quest.git

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cython
    - numpy
  run:
    - python {{ python }}
    - pyyaml
    - numpy
    - numba
    - scipy
    - numexpr
    - pytables
    - mdtraj=1.7.2
    - ipython
    - guiqwt
    - pyqt>=5.6.0
    - pymol

app:
    entry: quest
    summary: QuEst is a structure based fluorescence quenching estimator
    type: desk
    icon: logo.png

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: GPL3
  license_file: LICENSE
  summary: QuEst is a structure based fluorescence quenching estimator
  description:
    QuEst is a structure based fluorescence quenching estimator that simulates dynamic
    quenching of fluorescence decays of dyes that are coupled to the surface of a proteins.
    Dynamic fluorescence quenching is simulated by modelling (i) the diffusion of the dye
    and (ii) the quenching of the dye by surface exposed aromatic amino-acids.
extra:
  recipe-maintainers:
    - tpeulen
