package:
  name: avtraj
  version: "0.0.8"

source:
  git_rev: 0.0.8
  git_url: https://github.com/Fluorsescence-Tools/avtraj.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - mdtraj
    - LabelLib
    - numba

test:
  imports:
    - mdtraj
    - numba
    - LabelLib

about:
  home: https://github.com/Fluorescence-Tools/avtraj
  license: LGPL2.1
  license_file: LICENSE
