package:
  name: labellib
  version: "2018.12.5"

source:
  #git_tag: 2018.11.30pre3
  # Something is wrong in the way the CMake file processes the GIT version tag.
  # Hence, git_tag does not work (we can only build the most recent head)
  git_url: https://github.com/Fluorescence-Tools/LabelLib.git

requirements:
  host:
    - python {{ python }}
    - setuptools
    - numpy
  build:
    - python
    - numpy
    - eigen
    - pybind11
    - sphinx
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}

#build:
#  script: python setup.py bdist_wheel

test:
  imports:
    - LabelLib

about:
  home: https://github.com/Fluorescence-Tools/LabelLib
  license: LGPL v2.1
  license_family: LGPL
  summary: Python bindings for LabelLib
  description: LabelLib is a low-level C++ library for the simulation of small probes flexibly 
    coupled to biomolecules for the development of higher-level applications and libraries. LabelLib 
    can calculate the distribution of flexible labels around attachment points. Such probes are for 
    instance dyes for fluorescence spectroscopy, spin-labels for EPR and NMR, or chemical cross-links 
    for mass-spectrometry. Typically, these labels are fluorescent dyes. For such dyes LabelLib can 
    calculate FRET observables.
    
    LabelLib uses a coarse-grained approach to simulate the spatial distribution of probes around their 
    attachment point. In this coarse-grained approach, LabelLib determines the sterically accessible volume 
    of the probe considering the linker length and the spatial dimensions of the probe. The linker connecting 
    the probe to the biomolecule and the probe are approximated by a tube and soft sphere, respectively. 
    Details are provided in the publications
        
        1.  Kalinin, S., T. Peulen, S. Sindbert, P. J. Rothwell, S. Berger, T. Restle, R. S. Goody, 
            H. Gohlke and C. A. M. Seidel (2012). A toolkit and benchmark study for FRET-restrained 
            high-precision structural modeling. Nature Methods 9(12) 1218-U1129.
  
        2.  Dimura, M., T. O. Peulen, C. A. Hanke, A. Prakash, H. Gohlke and C. A. M. Seidel (2016). 
            Quantitative FRET studies and integrative modeling unravel the structure and dynamics 
            of biomolecular systems." Current Opinion in Structural Biology 40 163-185.
  
        3.  Sindbert, S., S. Kalinin, N. Hien, A. Kienzler, L. Clima, W. Bannwarth, B. Appel, 
            S. Muller and C. A. M. Seidel (2011). Accurate Distance Determination of Nucleic Acids 
            via Forster Resonance Energy Transfer - Implications of Dye Linker Length and Rigidity. 
            Journal of the American Chemical Society 133(8) 2463-2480.
            

