{% set name = "tttrlib" %}
{% set version="0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fluorescence-tools/{{ name }}/archive/{{ version }}.tar.gz
  sha256: bc57aa9130c1d8039d2dfba1ee5422b29c737fd2b429e5ae9bfb1f4ad1613c90

build:
    number: 0

requirements:
  build:
    - git
    - {{ compiler('cxx') }}
    - python {{ python }}
    - setuptools
    - cmake
    - numpy >=1.10
    - swig
    - openmp
  host:
    - python {{ python }}
    - setuptools
    - numpy >=1.10
    - hdf5 >=1.8.*
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - vs2015_runtime # [win]
    - hdf5 >=1.8.*

test:
  imports:
    - tttrlib

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: MPL 2.0
  summary: Python bindings for tttrlib
  description: |
    tttrlib C++ library including Python wrapper to read time-tagged
    time resolved data files.
  doc_url: https://fluorescence-tools.github.io/tttrlib/

extra:
  recipe-maintainers:
    - tpeulen
