{% set name = "tttrlib" %}
{% set version = "0.0.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/fluorescence-tools/tttrlib.git
  git_rev: "{{ version }}"
  #git_url: ..
  #path: ..

build:
    number: 0
    string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}

requirements:
  build:
    - git
    - {{ compiler('cxx') }}
    - python {{ python }}
    - setuptools
    - cmake
    - sphinx
    - swig
    - numpy >=1.10
    - hdf5 >=1.8.*
    - openmp
  host:
    - python {{ python }}
    - numpy >=1.10
    - hdf5 >=1.8.*
    - openmp
  run:
    - python {{ python }}
    - vs2015_runtime # [win]
    - {{ pin_compatible('numpy') }}
    - hdf5>=1.8.*

test:
  imports:
    - tttrlib

about:
  home: https://github.com/tpeulen/tttrlib
  license: MPL 2.0
  summary: Python bindings for tttrlib
  description: |
    tttrlib C++ library including Python wrapper to read time-tagged
    time resolved data files.
  doc_url: https://fluorescence-tools.github.io/tttrlib/

extra:
  recipe-maintainers:
    - tpeulen
