{% set name = "tttrlib" %}
{% set version = "0.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/fluorescence-tools/tttrlib.git
  git_rev: "{{ version }}"

build:
    number: 0
    string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy
    - swig
    - hdf5
    - cmake
    - sphinx
  run:
    - numpy
    - python {{ python }}
    - hdf5

test:
  imports:
    - tttrlib

about:
  home: https://github.com/tpeulen/tttrlib
  license: Mozilla Public License 2.0 (MPL 2.0)
  summary: Python bindings for tttrlib
  description: |
    tttrlib C++ library including Python wrapper to read time-tagged
    time resolved data files.
  doc_url: https://fluorescence-tools.github.io/tttrlib/

extra:
  recipe-maintainers:
    - tpeulen
