{% set name = "pycorrfit" %}
{% set version = "1.1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "946098511dbd9fda673ca527cbe00c0d2c59cfc602f21ec5ba2ae94be4a7761a"

build:
  number: 0
  entry_points:
    - pycorrfit=pycorrfit.gui.main:Main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - lmfit >=0.9.2
    - numpy >=1.14.2
    - pip
    - python
    - pyyaml >=3.12
    - scipy >=1.0.1
  run:
    - lmfit >=0.9.2
    - numpy >=1.14.2
    - python
    - pyyaml >=3.12
    - scipy >=1.0.1

test:
  imports:
    - pycorrfit
    - pycorrfit.gui
    - pycorrfit.gui.tools
    - pycorrfit.models
    - pycorrfit.readfiles
    - pycorrfit.readfiles.read_pt3_scripts
  commands:
    - pycorrfit --help
  requires:
    - pytest
    - simplejson
    - urllib3

about:
  home: "https://github.com/FCS-analysis/PyCorrFit"
  license: "GPL v2"
  license_family: "GPL2"
  license_file: ""
  summary: "Scientific tool for fitting correlation curves on a logarithmic plot."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - tpeulen
