package:
  name: chisurf
  version: "2018.12.1"

source:
  #git_rev: 18.9.18
  git_url: https://github.com/Fluorescence-Tools/ChiSurf.git

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}
  entry_points:
    - chisurf = chisurf:gui
  osx_is_app: True

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cython=0.24
    - numpy
  run:
    - python {{ python }}
    - pyyaml
    - python-slugify
    - numpy
    - numba
    - scipy
    - sympy
    - emcee
    - numexpr
    - pytables
    - mdtraj=1.7.2
    - ipython
    - matplotlib
    - pyqt>=5.6.0
    - pyqtgraph
    - qtconsole
    - qscintilla2
    - pyopengl
    - python-docx

app:
    entry: chisurf
    summary: Analysis tool for time-resolved fluorescence data
    type: desk
    icon: logo.png

outputs:
    - type: wheel
    - name: chisurf

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: GPL2.1
  license_file: LICENSE
    summary: ChiSurf is an interactive global analysis software for time-resolved fluorescence data
  description: ChiSurf is an interactive analysis software for time-resolved fluorescence data.
extra:
  recipe-maintainers:
    - tpeulen
