{% set name = "chisurf" %}
{% set version = "19.9.22" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Fluorescence-Tools/ChiSurf.git
  git_rev: "{{ version }}"

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}
  entry_points:
    - chisurf=chisurf:gui

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cython=0.24
    - numpy
  run:
    - python {{ python }}
    - pyyaml
    - python-slugify
    - numpy
    - numba
    - scipy
    - sympy
    - emcee
    - numexpr
    - pytables
    - mdtraj=1.7.2
    - ipython
    - matplotlib
    - pyqt>=5.6.0
    - pyqtgraph
    - qtconsole
    - qscintilla2
    - pyopengl
    - python-docx

outputs:
    - type: wheel
    - name: chisurf

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: GPL2.1
  license_file: LICENSE
  summary: ChiSurf is an interactive global analysis software for time-resolved fluorescence data
  description: ChiSurf is an interactive analysis software for time-resolved fluorescence data.

extra:
  recipe-maintainers:
    - tpeulen
